config/routes.rb
Rails.application.routes.draw do

  root to: 'jobs#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :jobs
  resources :rides
  resources :stays

end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user

  JOBS_CATEGORY = 0
  RIDES_CATEGORY = 1
  STAYS_CATEGORY = 2

  scope :by_jobs, lambda { where(category: JOBS_CATEGORY) }
  scope :by_rides, lambda { where(category: RIDES_CATEGORY) }
  scope :by_stays, lambda { where(category: STAYS_CATEGORY) }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :phone, presence: true

  has_secure_password

  def full_name
    first_name ? first_name + ' ' + last_name : email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  private

  def authenticate
    redirect_to login_path unless current_user
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @ads = Ad.by_jobs.paginate(page: params[:page])
  end

  def show
    @ad = Ad.by_jobs.find(params[:id])
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new
    @ad.category = JOBS_CATEGORY
    @ad.title = params[:title]
    @ad.description = params[:description]
    @ad.start_date = params[:start_date]
    @ad.end_date = params[:end_date]

    if @ad.save
      redirect_to jobs_path, notice: 'Ad posted.'
    else
      flash.now[:errors] = @ad.errors.full_messages
      render 'new'
    end
  end

end

app/controllers/map_controller.rb
class MapController < ApplicationController

  def index

  end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

  def index
    @ads = Ad.by_rides.paginate(page: params[:page])
  end

  def show
    @ad = Ad.by_rides.find(params[:id])
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new
    @ad.category = RIDES_CATEGORY
    @ad.title = params[:title]
    @ad.description = params[:description]
    @ad.start_date = params[:start_date]
    @ad.end_date = params[:end_date]

    if @ad.save
      redirect_to rides_path, notice: 'Ad posted.'
    else
      flash.now[:errors] = @ad.errors.full_messages
      render 'new'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Heyo'
    else
      flash.now[:error] = 'Invalid Credentials'
      @user ||= User.new
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'See ya'
  end

end

app/controllers/stays_controller.rb
class StaysController < ApplicationController

  def index
    @ads = Ad.by_stays.paginate(page: params[:page])
  end

  def show
    @ad = Ad.by_stays.find(params[:id])
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new
    @ad.category = STAYS_CATEGORY
    @ad.title = params[:title]
    @ad.description = params[:description]
    @ad.start_date = params[:start_date]
    @ad.end_date = params[:end_date]

    if @ad.save
      redirect_to stays_path, notice: 'Ad posted.'
    else
      flash.now[:errors] = @ad.errors.full_messages
      render 'new'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:email]
    @user.password = params[:password]
    @user.avatar = Faker::Avatar.image
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.age = params[:age]
    @user.phone = params[:phone]

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Heya'
    else
      flash.now[:errors] = @user.errors.full_messages
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    render 'show' if @user.id != current_user.id
  end

  def update
    @user = User.find(params[:id])
    @user.email = params[:email]
    @user.password = params[:password] if params[:password].present?
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.age = params[:age]
    @user.phone = params[:phone]
    binding.pry

    if @user.save
      redirect_to user_path(@user), notice: 'Got it'
    else
      flash.now[:errors] = @user.errors.full_messages
      render 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/index.html.slim
h2 Jobs

= will_paginate @ads
table.table
  thead
    tr
      th Posted
      th Title
      th Posted by
  tbody
    - @ads.each do |ad|
      tr
        td = ad.created_at.strftime('%m/%d/%y')
        td = link_to ad.title, job_path(ad)
        td
          = image_tag(ad.user.avatar, alt: '') if ad.user.avatar
          span = ad.user.full_name

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Nomads
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta name='viewport' content='width=device-width, initial-scale=1.0'
  body
    #header
      .container
        .row
          .col-md-4
            .brand
              a href='/'
                h1 <i class="fa fa-th-large"></i>Nomads
          .col-md-8
            .mobile-user-nav
              - if current_user
                p Howdy ho <b>#{current_user.email}</b>
                = link_to 'Profile', user_path(current_user)
                = link_to 'Logout', logout_path
              - else
                = link_to 'Join Us', new_user_path
                = link_to 'Login', login_path
            .user-nav
              - if current_user
                p Howdy ho <b>#{current_user.email}</b>
                .pull-right
                  = link_to 'Profile', user_path(current_user)
                  = link_to 'Logout', logout_path
              - else
                = form_tag login_path, class: 'form form-inline' do
                  .form-group
                    = label_tag :email
                    = email_field_tag :email
                  .form-group
                    = label_tag :password
                    = password_field_tag :password
                  .form-group
                    = submit_tag 'Login', class: 'btn btn-default'
                  .form-group
                    span.mobile-message Not one of us?
                    = link_to 'Join Us', new_user_path, class: 'register'
        .row
          .categories
            .col-md-4
              = link_to 'Jobs', jobs_path
            .col-md-4
              = link_to 'Rides', rides_path
            .col-md-4
              = link_to 'Stays', stays_path
    .container
      - if flash[:notice]
        p.notice = flash[:notice]
      - if flash[:error]
        p.error = flash[:error]
      - if flash[:errors]
        ul.error
          - flash[:errors].each do |error|
            li = error
      #viewport
        = yield

app/views/rides/index.html.slim
h2 Rides

= will_paginate @ads
table.table
  thead
    tr
      th Posted
      th Date Offered
      th Title
      th Posted by
  tbody
    - @ads.each do |ad|
      tr
        td = ad.created_at.strftime('%m/%d/%y')
        td = ad.start_date.strftime('%m/%d/%y')
        td = link_to ad.title, job_path(ad)
        td
          = image_tag(ad.user.avatar, alt: '') if ad.user.avatar
          span = ad.user.full_name

app/views/stays/index.html.slim
h2 Stays

= will_paginate @ads
table.table
  thead
    tr
      th Posted
      th Title
      th Posted by
  tbody
    - @ads.each do |ad|
      tr
        td = ad.created_at.strftime('%m/%d/%y')
        td = link_to ad.title, job_path(ad)
        td
          = image_tag(ad.user.avatar, alt: '') if ad.user.avatar
          span = ad.user.full_name

app/views/users/edit.html.slim
= form_tag user_path(@user), method: 'PUT', class: 'form center-form' do
  h2 Edit Profile

  .form-group
    .row
      .col-md-4
        = label_tag :email
      .col-md-8
        = email_field_tag :email, @user.email
  .form-group
    .row
      .col-md-4
        = label_tag :password
      .col-md-8
        = password_field_tag :password
  .form-group
    .row
      .col-md-4
        = label_tag :first_name
      .col-md-8
        = text_field_tag :first_name
  .form-group
    .row
      .col-md-4
        = label_tag :last_name
      .col-md-8
        = text_field_tag :last_name
  .form-group
    .row
      .col-md-4
        = label_tag :age
      .col-md-8
        = number_field_tag :age
  .form-group
    .row
      .col-md-4
        = label_tag :phone
      .col-md-8
        = phone_field_tag :phone
  .form-group
    = submit_tag 'Update', class: 'btn btn-default btn-block'
    span.alternative
      span Changed your mind?
      = link_to 'Cancel', user_path(@user.id)

app/views/users/new.html.slim
= form_tag users_path, class: 'form center-form' do
  h2 Register

  .form-group
    .row
      .col-md-4
        = label_tag :first_name
      .col-md-8
        = text_field_tag :first_name, @user.first_name
  .form-group
    .row
      .col-md-4
        = label_tag :last_name
      .col-md-8
        = text_field_tag :last_name, @user.last_name
  .form-group
    .row
      .col-md-4
        = label_tag :age
      .col-md-8
        = number_field_tag :age, @user.age
  .form-group
    .row
      .col-md-4
        = label_tag :phone
      .col-md-8
        = phone_field_tag :phone, @user.phone
  .form-group
    .row
      .col-md-4
        = label_tag :email
      .col-md-8
        = email_field_tag :email, @user.email
  .form-group
    .row
      .col-md-4
        = label_tag :password
      .col-md-8
        = password_field_tag :password
  .form-group
    = submit_tag 'Embark', class: 'btn btn-default btn-block'
    span.alternative
      span Already with us?
      = link_to 'Login', login_path

app/views/users/show.html.slim
.center-form.profile
  .row
    .col-md-6
      h2 Profile
    .col-md-6
      - if @user.id == current_user.id
        = link_to 'Edit', edit_user_path(@user), class: 'edit'

  .row
    .col-md-3
      strong Avatar
    .col-md-9
      img.attr src=@user.avatar
  .row
    .col-md-3
      strong Email
    .col-md-9
      span.attr = @user.email
  .row
    .col-md-3
      strong First Name
    .col-md-9
      span.attr = @user.first_name
  .row
    .col-md-3
      strong Last Name
    .col-md-9
      span.attr = @user.last_name
  .row
    .col-md-3
      strong Age
    .col-md-9
      span.attr = @user.age
  .row
    .col-md-3
      strong Phone
    .col-md-9
      span.attr = @user.phone